### PR TITLE
Hamburger shows/hides menu on mobile

### LINKED ISSUE #20: [Home] Fix burger button
Maybe solve using a field & toggle method?

Template:
```vue
<!-- burger -->
@click="toggleMenu"

<!-- mobile menu -->
v-if="showMobileMenu"
```

Script:
```ts
showMobileMenu=false

toggleMenu(): void {
  this.showMobileMenu = !this.showMobileMenu
}
```

### PR DESCRIPTION
**Pull request by antonyharfield**
## ✅ DoD

- [x] All work is complete
- [x] Migrations: NA
- [x] Documentation: NA
- [x] Release notes: NA
- [x] Issues linked: resolves #20 

## 🛑 Problems

- Not sure if I did the right thing with the right button padding?

## 📝 Summary

- Hamburger shows/hides menu on mobile
- _"Add an event" right nav bar button is compressed on mobile_
- _"Add an event" has subtler background normally, and crazy background on hover_

## 💡 More ideas

I thought about changing it to be "Share an event", but we already have quite a few different words ("add", "create", "host", "suggest"). We might want to tidy our verbiage! Is that the right word? :p

## 📸 Screenshots

Screenshot 2021-05-11 at 08 19 34

### CODE REVIEW

**Comment by charles-allen** [comment]
1. It's [not clear to me](https://github.com/kaorun343/vue-property-decorator/issues/294) if `@Ref` from `vue-property-decorator` is the "Vue-3" way to manage refs. There was [a lot of discussion about `@Prop`](https://github.com/vuejs/vue-class-component/issues/465) which I consider semi-deprecated (because that design cannot support types). I don't know how this extends to `@Ref` (if at all); if it works for now, I guess let's do it; and just keep it in mind.

2. I don't know if there's precedent on iOS. The closest to this on Android is a navigation drawer. If you click a menu item, it closes the drawer too. I think on balance I slightly prefer that vs keeping the drawer open. It's a quick fix, so I'll commit it and we can revert if we decide not to go that way.

3. I'm also not sure about the lingering focus ring on the hamburger after closing the menu & mousing away - I think this is also an easy fix; so let's try it :)  
    
    Screen Shot 2021-05-11 at 22 04 21

**Comment by charles-allen** [comment]
I was seeing warnings related to vue-property-decorator (which I think mean `vue-property-decorator` & `vue-class-component` aren't in sync):

Screen Shot 2021-05-11 at 22 38 42

I've updated to `vue-property-decorator@next`, which seems to have sync'd the 2 libs & fixed the warnings. Everything still seems to work :)

**Review by charles-allen — APPROVED** [review]
LGTM. I made a couple of tweaks that I prefer; but we can revert if necessary.

noice

**Comment by antonyharfield** [comment]
Noice tweaks!

**Pull request merged**
